inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageChain:
  Exclude:
    - 'spec/**/*.rb'
