inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/solr_indexable.rb'

Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/parent_oids.rake'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/solr_indexable.rb'

Metrics/MethodLength:
    Exclude:
      - 'app/models/concerns/solr_indexable.rb'

Metrics/ClassLength:
    Exclude:
      - 'app/models/iiif_presentation.rb'
      - 'app/controllers/parent_objects_controller.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/json_helper.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageChain:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/**/*.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*.rb'

Rails/SaveBang:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'