inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'spec/**/*.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/lib/activity_stream_reader_spec.rb'
