approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

# 30 days in minutes
npmMinimalAgeGate: 43200

# use for packages that need to be within 30 day window
# npmPreapprovedPackages:

yarnPath: .yarn/releases/yarn-4.18.0.cjs
