version: '3'
services:

  web:
    build: .
    image: '${REGISTRY_HOST}${REGISTRY_URI}:master'
    env_file:
      - .env
      - .secrets
    ports:
      - '3001:3001'
    volumes:
      - .:/home/app/webapp:cached
      - node_modules:/home/app/webapp/node_modules
      - rails_cache:/home/app/webapp/tmp/cache
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    depends_on:
      - db
      - solr

  db:
    image: yalelibraryit/dc-postgres:${POSTGRES_VERSION:-latest}
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_VERSION:-latest}
    ports:
      - '8983:8983'
    volumes:
      - solr:/opt/solr/server/solr/mycores
    env_file:
      - .env
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

volumes:
  postgres:
  solr:
  node_modules:
  rails_cache:
