
version: '2.1'
services:

  base:
    image: '${REGISTRY_HOST}${REGISTRY_URI}:latest'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
