
version: '2.1'
services:

  base:
    image: '${REGISTRY_HOST}${REGISTRY_URI}-base:${MANAGEMENT_BASE_TAG:-latest}'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.base

  web:
    build: .
    image: '${REGISTRY_HOST}${REGISTRY_URI}:${MANAGEMENT_TAG:-latest}'
    env_file:
      - .env
      - .env.development
      - .env.test
      - .secrets
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/webapp
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    depends_on:
      - db
      - solr

  db:
    image: postgres
    env_file:
      - .env
      - .env.development
      - .env.test
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG:-latest}
    ports:
      - '8983:8983'
    volumes:
      - solr:/opt/solr/server/solr/mycores
    env_file:
      - .env
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

volumes:
  postgres:
  solr:
