sut:
  build: .
  environment:	
    POSTGRES_HOST: localhost
    POSTGRES_DB: yul_dc_management_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    SOLR_CORE: blacklight-test
    SOLR_URL: http://localhost:8983/solr
  command: bundle exec rspec --tag ~vpn_only:true
