 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/batch_process_events", type: :request do
  # BatchProcessEvent. As you add validations to BatchProcessEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BatchProcessEvent.create! valid_attributes
      get batch_process_events_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      get batch_process_event_url(batch_process_event)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_batch_process_event_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      get edit_batch_process_event_url(batch_process_event)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BatchProcessEvent" do
        expect {
          post batch_process_events_url, params: { batch_process_event: valid_attributes }
        }.to change(BatchProcessEvent, :count).by(1)
      end

      it "redirects to the created batch_process_event" do
        post batch_process_events_url, params: { batch_process_event: valid_attributes }
        expect(response).to redirect_to(batch_process_event_url(BatchProcessEvent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BatchProcessEvent" do
        expect {
          post batch_process_events_url, params: { batch_process_event: invalid_attributes }
        }.to change(BatchProcessEvent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post batch_process_events_url, params: { batch_process_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested batch_process_event" do
        batch_process_event = BatchProcessEvent.create! valid_attributes
        patch batch_process_event_url(batch_process_event), params: { batch_process_event: new_attributes }
        batch_process_event.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the batch_process_event" do
        batch_process_event = BatchProcessEvent.create! valid_attributes
        patch batch_process_event_url(batch_process_event), params: { batch_process_event: new_attributes }
        batch_process_event.reload
        expect(response).to redirect_to(batch_process_event_url(batch_process_event))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        batch_process_event = BatchProcessEvent.create! valid_attributes
        patch batch_process_event_url(batch_process_event), params: { batch_process_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested batch_process_event" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      expect {
        delete batch_process_event_url(batch_process_event)
      }.to change(BatchProcessEvent, :count).by(-1)
    end

    it "redirects to the batch_process_events list" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      delete batch_process_event_url(batch_process_event)
      expect(response).to redirect_to(batch_process_events_url)
    end
  end
end
