# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/batch_process_events", type: :request do
  # BatchProcessEvent. As you add validations to BatchProcessEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      BatchProcessEvent.create! valid_attributes
      get batch_process_events_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      get batch_process_event_url(batch_process_event)
      expect(response).to be_successful
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested batch_process_event" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      expect do
        delete batch_process_event_url(batch_process_event)
      end.to change(BatchProcessEvent, :count).by(-1)
    end

    it "redirects to the batch_process_events list" do
      batch_process_event = BatchProcessEvent.create! valid_attributes
      delete batch_process_event_url(batch_process_event)
      expect(response).to redirect_to(batch_process_events_url)
    end
  end
end
