# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/goobi_xml_imports", type: :request do
  # GoobiXmlImport. As you add validations to GoobiXmlImport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      GoobiXmlImport.create! valid_attributes
      get goobi_xml_imports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      goobi_xml_import = GoobiXmlImport.create! valid_attributes
      get goobi_xml_import_url(goobi_xml_import)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_goobi_xml_import_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      goobi_xml_import = GoobiXmlImport.create! valid_attributes
      get edit_goobi_xml_import_url(goobi_xml_import)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GoobiXmlImport" do
        expect do
          post goobi_xml_imports_url, params: { goobi_xml_import: valid_attributes }
        end.to change(GoobiXmlImport, :count).by(1)
      end

      it "redirects to the created goobi_xml_import" do
        post goobi_xml_imports_url, params: { goobi_xml_import: valid_attributes }
        expect(response).to redirect_to(goobi_xml_import_url(GoobiXmlImport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GoobiXmlImport" do
        expect do
          post goobi_xml_imports_url, params: { goobi_xml_import: invalid_attributes }
        end.to change(GoobiXmlImport, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post goobi_xml_imports_url, params: { goobi_xml_import: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested goobi_xml_import" do
        goobi_xml_import = GoobiXmlImport.create! valid_attributes
        patch goobi_xml_import_url(goobi_xml_import), params: { goobi_xml_import: new_attributes }
        goobi_xml_import.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the goobi_xml_import" do
        goobi_xml_import = GoobiXmlImport.create! valid_attributes
        patch goobi_xml_import_url(goobi_xml_import), params: { goobi_xml_import: new_attributes }
        goobi_xml_import.reload
        expect(response).to redirect_to(goobi_xml_import_url(goobi_xml_import))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        goobi_xml_import = GoobiXmlImport.create! valid_attributes
        patch goobi_xml_import_url(goobi_xml_import), params: { goobi_xml_import: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested goobi_xml_import" do
      goobi_xml_import = GoobiXmlImport.create! valid_attributes
      expect do
        delete goobi_xml_import_url(goobi_xml_import)
      end.to change(GoobiXmlImport, :count).by(-1)
    end

    it "redirects to the goobi_xml_imports list" do
      goobi_xml_import = GoobiXmlImport.create! valid_attributes
      delete goobi_xml_import_url(goobi_xml_import)
      expect(response).to redirect_to(goobi_xml_imports_url)
    end
  end
end
