# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/metadata_samples", type: :request do
  let(:user) { FactoryBot.create(:user) }
  # MetadataSample. As you add validations to MetadataSample, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  before do
    login_as(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      MetadataSample.create! valid_attributes
      get metadata_samples_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      metadata_sample = MetadataSample.create! valid_attributes
      get metadata_sample_url(metadata_sample)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_metadata_sample_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      metadata_sample = MetadataSample.create! valid_attributes
      get edit_metadata_sample_url(metadata_sample)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MetadataSample" do
        expect do
          post metadata_samples_url, params: { metadata_sample: valid_attributes }
        end.to change(MetadataSample, :count).by(1)
      end

      it "redirects to the created metadata_sample" do
        post metadata_samples_url, params: { metadata_sample: valid_attributes }
        expect(response).to redirect_to(metadata_sample_url(MetadataSample.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MetadataSample" do
        expect do
          post metadata_samples_url, params: { metadata_sample: invalid_attributes }
        end.to change(MetadataSample, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post metadata_samples_url, params: { metadata_sample: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested metadata_sample" do
        metadata_sample = MetadataSample.create! valid_attributes
        patch metadata_sample_url(metadata_sample), params: { metadata_sample: new_attributes }
        metadata_sample.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the metadata_sample" do
        metadata_sample = MetadataSample.create! valid_attributes
        patch metadata_sample_url(metadata_sample), params: { metadata_sample: new_attributes }
        metadata_sample.reload
        expect(response).to redirect_to(metadata_sample_url(metadata_sample))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        metadata_sample = MetadataSample.create! valid_attributes
        patch metadata_sample_url(metadata_sample), params: { metadata_sample: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested metadata_sample" do
      metadata_sample = MetadataSample.create! valid_attributes
      expect do
        delete metadata_sample_url(metadata_sample)
      end.to change(MetadataSample, :count).by(-1)
    end

    it "redirects to the metadata_samples list" do
      metadata_sample = MetadataSample.create! valid_attributes
      delete metadata_sample_url(metadata_sample)
      expect(response).to redirect_to(metadata_samples_url)
    end
  end
end
