# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mets_xml_imports", type: :request do
  let(:user) { FactoryBot.create(:user) }
  # MetsXmlImport. As you add validations to MetsXmlImport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  before do
    login_as user
  end

  describe "GET /index" do
    it "renders a successful response" do
      MetsXmlImport.create! valid_attributes
      get mets_xml_imports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mets_xml_import = MetsXmlImport.create! valid_attributes
      get mets_xml_import_url(mets_xml_import)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mets_xml_import_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mets_xml_import = MetsXmlImport.create! valid_attributes
      get edit_mets_xml_import_url(mets_xml_import)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MetsXmlImport" do
        expect do
          post mets_xml_imports_url, params: { mets_xml_import: valid_attributes }
        end.to change(MetsXmlImport, :count).by(1)
      end

      it "redirects to the created mets_xml_import" do
        post mets_xml_imports_url, params: { mets_xml_import: valid_attributes }
        expect(response).to redirect_to(mets_xml_import_url(MetsXmlImport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MetsXmlImport" do
        expect do
          post mets_xml_imports_url, params: { mets_xml_import: invalid_attributes }
        end.to change(MetsXmlImport, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mets_xml_imports_url, params: { mets_xml_import: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested mets_xml_import" do
        mets_xml_import = MetsXmlImport.create! valid_attributes
        patch mets_xml_import_url(mets_xml_import), params: { mets_xml_import: new_attributes }
        mets_xml_import.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mets_xml_import" do
        mets_xml_import = MetsXmlImport.create! valid_attributes
        patch mets_xml_import_url(mets_xml_import), params: { mets_xml_import: new_attributes }
        mets_xml_import.reload
        expect(response).to redirect_to(mets_xml_import_url(mets_xml_import))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mets_xml_import = MetsXmlImport.create! valid_attributes
        patch mets_xml_import_url(mets_xml_import), params: { mets_xml_import: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mets_xml_import" do
      mets_xml_import = MetsXmlImport.create! valid_attributes
      expect do
        delete mets_xml_import_url(mets_xml_import)
      end.to change(MetsXmlImport, :count).by(-1)
    end

    it "redirects to the mets_xml_imports list" do
      mets_xml_import = MetsXmlImport.create! valid_attributes
      delete mets_xml_import_url(mets_xml_import)
      expect(response).to redirect_to(mets_xml_imports_url)
    end
  end
end
