# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/parent_objects", type: :request, prep_metadata_sources: true, prep_admin_sets: true do
  let(:user) { FactoryBot.create(:sysadmin_user) }
  # ParentObject. As you add validations to ParentObject, be sure to
  # adjust the attributes here as well.
  before do
    stub_metadata_cloud("2004628")
    login_as user
  end

  let(:valid_params) do
    {
      oid: "2004628",
      authoritative_metadata_source_id: 1,
      admin_set: 'brbl',
      visibility: "Private"
    }
  end

  let(:invalid_params) do
    {
      oid: "2004628",
      authoritative_metadata_source_id: 4,
      visibility: nil,
      admin_set: 'brbl'
    }
  end

  let(:valid_attributes) do
    {
      oid: "2004628",
      authoritative_metadata_source_id: 1,
      admin_set: AdminSet.find_by_key('brbl'),
      bib: "123"
    }
  end

  let(:valid_preservica_attributes) do
    {
      oid: "200000000",
      authoritative_metadata_source_id: 1,
      admin_set: AdminSet.find_by_key('brbl'),
      bib: "123",
      preservica_uri: '/preservica/api/entity/structural-objects/7fe35e8c-c21a-444a-a2e2-e3c926b519c5',
      preservica_representation_name: 'Preservation-1'
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      ParentObject.create! valid_attributes
      get parent_objects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parent_object = ParentObject.create! valid_attributes
      get parent_object_url(parent_object)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parent_object_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      parent_object = ParentObject.create! valid_attributes
      get edit_parent_object_url(parent_object)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ParentObject" do
        expect do
          post parent_objects_url, params: { parent_object: valid_params }
        end.to change(ParentObject, :count).by(1)
          .and change(BatchProcess, :count).by(1)
      end

      it "redirects to the created parent_object" do
        post parent_objects_url, params: { parent_object: valid_params }
        expect(response).to redirect_to(parent_object_url(ParentObject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ParentObject" do
        expect do
          post parent_objects_url, params: { parent_object: invalid_params }
        end.to change(ParentObject, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post parent_objects_url, params: { parent_object: invalid_params }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        {
          authoritative_metadata_source_id: 2,
          admin_set: 'brbl'
        }
      end

      it "updates the requested parent_object" do
        parent_object = ParentObject.create! valid_attributes
        patch parent_object_url(parent_object), params: { parent_object: new_attributes }
        parent_object.reload
        expect(parent_object.authoritative_metadata_source_id).to eq 2
      end

      it "queues metadata update after it updates parent_object" do
        parent_object = ParentObject.create! valid_attributes
        # rubocop:disable RSpec/AnyInstance
        expect_any_instance_of(ParentObjectsController).to receive(:queue_parent_metadata_update)
        # rubocop:enable RSpec/AnyInstance
        patch parent_object_url(parent_object), params: { parent_object: new_attributes }
        parent_object.reload
        expect(parent_object.authoritative_metadata_source_id).to eq 2
      end

      it "redirects to the parent_object" do
        parent_object = ParentObject.create! valid_attributes
        patch parent_object_url(parent_object), params: { parent_object: new_attributes }
        parent_object.reload
        expect(response).to redirect_to(parent_object_url(parent_object))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parent_object = ParentObject.create! valid_attributes
        patch parent_object_url(parent_object), params: { parent_object: invalid_params }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parent_object" do
      parent_object = ParentObject.create! valid_attributes
      expect do
        delete parent_object_url(parent_object)
      end.to change(ParentObject, :count).by(-1)
        .and change(BatchProcess, :count).by(0)
    end

    it "can still access the BatchProcess page" do
      parent_object = ParentObject.create! valid_attributes
      delete parent_object_url(parent_object)
      expect(get(batch_processes_url)).to eq 200
    end

    it "redirects to the parent_objects list" do
      parent_object = ParentObject.create! valid_attributes
      delete parent_object_url(parent_object)
      expect(response).to redirect_to(parent_objects_url)
    end
  end

  describe "#reindex" do
    it 'redirects to the parent_objects list' do
      post reindex_parent_objects_url
      expect(response).to redirect_to(parent_objects_url)
      expect(flash[:notice]).to eq('Parent objects have been reindexed.')
    end
  end

  describe "#all_metadata" do
    it 'redirects to the parent_objects list' do
      ParentObject.create! valid_attributes
      post all_metadata_parent_objects_url
      expect(response).to redirect_to(parent_objects_url)
      expect(flash[:notice]).to eq('Parent objects have been queued for metadata update.')
    end
  end

  describe '#update_metadata' do
    it 'redirects to the parent_objects list' do
      parent_object = ParentObject.create! valid_attributes
      post update_metadata_parent_object_url(parent_object)
      expect(response).to redirect_to(parent_object_url(parent_object))
      expect(flash[:notice]).to eq('This object has been queued for a metadata update.')
    end
  end

  describe '#sync_from_preservica' do
    around do |example|
      preservica_host = ENV['PRESERVICA_HOST']
      preservica_creds = ENV['PRESERVICA_CREDENTIALS']
      ENV['PRESERVICA_HOST'] = "testpreservica"
      ENV['PRESERVICA_CREDENTIALS'] = '{"brbl": {"username":"xxxxx", "password":"xxxxx"}}'
      access_host = ENV['ACCESS_MASTER_MOUNT']
      ENV['ACCESS_MASTER_MOUNT'] = File.join("spec", "fixtures", "images", "access_masters")
      perform_enqueued_jobs do
        example.run
      end
      ENV['PRESERVICA_HOST'] = preservica_host
      ENV['PRESERVICA_CREDENTIALS'] = preservica_creds
      ENV['ACCESS_MASTER_MOUNT'] = access_host
    end

    before do
      stub_metadata_cloud("AS-200000000", "aspace")
      stub_request(:post, "https://testpreservica/api/accesstoken/login").to_return(status: 200, body: '{"token":"test"}')
      stub_request(:post, "https://testpreservica/api/accesstoken/refresh").to_return(status: 200, body: '{"token":"test"}')
      fixtures = %w[preservica/api/entity/structural-objects/7fe35e8c-c21a-444a-a2e2-e3c926b519c5/children
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3r/representations
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3r/representations/Access-2
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3r/representations/Preservation-1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b486/generations
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b486/generations/1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b486/generations/1/bitstreams/1
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3d/representations
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3d/representations/Access-2
                    preservica/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3d/representations/Preservation-1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b489/generations
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b489/generations/1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b489/generations/1/bitstreams/1
                    preservica/api/entity/information-objects/f44ba97e-af2b-498e-b118-ed1247822f44/representations
                    preservica/api/entity/information-objects/f44ba97e-af2b-498e-b118-ed1247822f44/representations/Access-2
                    preservica/api/entity/information-objects/f44ba97e-af2b-498e-b118-ed1247822f44/representations/Preservation-1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b487/generations
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b487/generations/1
                    preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b487/generations/1/bitstreams/1]

      fixtures.each do |fixture|
        stub_request(:get, "https://test#{fixture}").to_return(
          status: 200, body: File.open(File.join(fixture_path, "#{fixture}.xml"))
        )
      end
      stub_request(:get, "https://testpreservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b487/generations/1/bitstreams/1/content").to_return(
        status: 200, body: File.open(File.join(fixture_path, "preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b487/generations/1/bitstreams/1/content.tif"), 'rb')
      )
      stub_request(:get, "https://testpreservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b486/generations/1/bitstreams/1/content").to_return(
        status: 200, body: File.open(File.join(fixture_path, "preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b486/generations/1/bitstreams/1/content.tif"), 'rb')
      )
      stub_request(:get, "https://testpreservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b489/generations/1/bitstreams/1/content").to_return(
        status: 200, body: File.open(File.join(fixture_path, "preservica/api/entity/content-objects/ae328d84-e429-4d46-a865-9ee11157b489/generations/1/bitstreams/1/content.tif"), 'rb')
      )
    end

    it 'redirects to the parent_objects list' do
      parent_object = ParentObject.create! valid_preservica_attributes
      expect(parent_object.child_objects.count).to eq 0
      post sync_from_preservica_parent_object_url(parent_object)
      expect(response).to redirect_to(parent_object_url(parent_object))
      expect(flash[:notice]).to eq('This object has been queued for synchronization of child objects from Preservica.')
    end
  end

  describe '#minify' do
    let(:redirect_attributes) do
      {
        redirect_to: 'https://collections.library.yale.edu/catalog/123'
      }
    end

    let(:invalid_redirect_params) do
      {
        redirect_to: 'https://collections.library.yale.educcccatalog/123'
      }
    end

    it 'reduces the parent record to a smaller record' do
      parent_object = ParentObject.create! valid_attributes
      expect(parent_object.bib).to eq("123")
      patch parent_object_url(parent_object), params: { parent_object: redirect_attributes }
      parent_object.reload
      expect(parent_object.bib).to be_nil
      expect(parent_object.digital_object_source).to be_nil
      expect(parent_object.preservica_uri).to be_nil
      expect(parent_object.visibility).to eq 'Redirect'
      expect(parent_object.admin_set.key).to eq 'brbl'
      expect(parent_object.redirect_to).to eq 'https://collections.library.yale.edu/catalog/123'
    end

    it 'can display redirected non-ladybird parents' do
      parent_object = ParentObject.create! valid_attributes
      expect(parent_object.bib).to eq("123")
      patch parent_object_url(parent_object), params: { parent_object: redirect_attributes.merge(authoritative_metadata_source_id: 2) }
      parent_object.reload
      get parent_object_url(parent_object)
      expect(response).to be_successful
    end

    it 'redirects to the parent show page' do
      parent_object = ParentObject.create! valid_attributes
      patch parent_object_url(parent_object), params: { parent_object: redirect_attributes }
      parent_object.reload
      expect(response).to redirect_to(parent_object_url(parent_object))
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parent_object = ParentObject.create! valid_attributes
        patch parent_object_url(parent_object), params: { parent_object: invalid_redirect_params }
        expect(response).to be_successful
      end
    end
  end

  context 'without sys admin privileges' do
    let(:user) { FactoryBot.create(:user) }
    before do
      login_as user
    end

    describe '#reindex' do
      it 'is not allowed' do
        post reindex_parent_objects_url
        expect(response).to have_http_status(:unauthorized)
      end
    end

    describe "#all_metadata" do
      it 'is not allowed' do
        post all_metadata_parent_objects_url
        expect(response).to have_http_status(:unauthorized)
      end
    end
  end
end
