# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/redirected_parent_objects", type: :request, prep_metadata_sources: true, prep_admin_sets: true do
  let(:user) { FactoryBot.create(:sysadmin_user) }
  # ParentObject. As you add validations to ParentObject, be sure to
  # adjust the attributes here as well.
  before do
    stub_metadata_cloud("2004628")
    login_as user
  end

  let(:valid_attributes) do
    {
      oid: "2004628",
      authoritative_metadata_source_id: 1,
      admin_set: AdminSet.find_by_key('brbl'),
      bib: "123",
      redirect_to: 'https://collections-uat.library.yale.edu/catalog/234567',
      visibility: 'Redirect'
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      ParentObject.create! valid_attributes
      get redirected_parent_objects_url
      expect(response).to be_successful
    end
  end
end
